"""Añadir columna enviado

Revision ID: 681f104e9d88
Revises: cc6287a084c8
Create Date: 2023-09-13 14:26:41.441399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681f104e9d88'
down_revision = 'cc6287a084c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enviado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracto', schema=None) as batch_op:
        batch_op.drop_column('enviado')

    # ### end Alembic commands ###
