"""First db app migrate

Revision ID: 81acdd231ea6
Revises: 
Create Date: 2023-08-16 13:22:11.304138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81acdd231ea6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('id_contacto', sa.String(length=20), nullable=False),
    sa.Column('nombre_titular', sa.String(length=80), nullable=False),
    sa.Column('telefono_1', sa.String(length=20), nullable=True),
    sa.Column('telefono_2', sa.String(length=20), nullable=True),
    sa.Column('telefono_3', sa.String(length=20), nullable=True),
    sa.Column('mail_1', sa.String(length=80), nullable=True),
    sa.Column('mail_2', sa.String(length=80), nullable=True),
    sa.Column('mail_3', sa.String(length=80), nullable=True),
    sa.Column('periodo', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.String(length=20), nullable=False),
    sa.Column('id_contacto', sa.String(length=20), nullable=False),
    sa.Column('periodo', sa.Date(), nullable=True),
    sa.Column('codigo_de_cargue', sa.String(length=100), nullable=True),
    sa.Column('tipo_extracto', sa.String(length=100), nullable=True),
    sa.Column('visitado', sa.Boolean(), nullable=True),
    sa.Column('veces_visitado', sa.Integer(), nullable=False),
    sa.Column('ultima_visita', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.String(length=20), nullable=False),
    sa.Column('periodo', sa.Date(), nullable=True),
    sa.Column('numero_producto', sa.String(length=20), nullable=True),
    sa.Column('dia_pago', sa.Date(), nullable=True),
    sa.Column('valor_cuota_mensual', sa.Float(), nullable=True),
    sa.Column('valor_mora', sa.Float(), nullable=True),
    sa.Column('dias_mora', sa.Integer(), nullable=True),
    sa.Column('siguiente_pago', sa.Date(), nullable=True),
    sa.Column('numero_obligaciones', sa.Integer(), nullable=True),
    sa.Column('saldo_total', sa.Float(), nullable=True),
    sa.Column('meses_castigo', sa.Integer(), nullable=True),
    sa.Column('fecha_corte', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto')
    op.drop_table('extracto')
    op.drop_table('cliente')
    # ### end Alembic commands ###
