"""Añadir columna enviado default falsee

Revision ID: cc9cf8d5b803
Revises: 681f104e9d88
Create Date: 2023-09-13 14:37:51.391286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9cf8d5b803'
down_revision = '681f104e9d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracto', schema=None) as batch_op:
        batch_op.alter_column('enviado',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracto', schema=None) as batch_op:
        batch_op.alter_column('enviado',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
